all:
	javac Calculador_de_Coloracion_Ej1.java Nodo_Coloreable.java ColoresPosiblesEj1.java Nodo_Dirigido_Compacto.java ColoresPosibles.java Nodo_Dirigido.java Escritor.java Nodo_Dirigido_SAT.java Lector.java Nodo_Abstracto.java Tester.java -classpath ../lib/junit__V4.4__I2007.07.19.jar
	mv Calculador_de_Coloracion_Ej1.class ../bin1/Calculador_de_Coloracion_Ej1.class
	mv Nodo_Coloreable.class ../bin1/Nodo_Coloreable.class
	mv ColoresPosiblesEj1.class ../bin1/ColoresPosiblesEj1.class
	mv Nodo_Dirigido_Compacto.class ../bin1/Nodo_Dirigido_Compacto.class
	mv ColoresPosibles.class ../bin1/ColoresPosibles.class
	mv Nodo_Dirigido.class ../bin1/Nodo_Dirigido.class
	mv Escritor.class ../bin1/Escritor.class
	mv Nodo_Dirigido_SAT.class ../bin1/Nodo_Dirigido_SAT.class
	mv Lector.class ../bin1/Lector.class
	mv Nodo_Abstracto.class ../bin1/Nodo_Abstracto.class
	mv Tester.class ../bin1/Tester.class
	mv 'Tester$$Nodo_Tester.class' ../bin1/'Tester$$Nodo_Tester.class'
