all:
	javac Calculador_de_Coloracion_Ej1.java Nodo_Coloreable.java ColoresPosiblesEj1.java Nodo_Dirigido_Compacto.java ColoresPosibles.java Nodo_Dirigido.java Escritor.java Nodo_Dirigido_SAT.java Indice_colores_ej1.java Nodo_Grafo_Dirigido_2.java Indice_colores.java Nodo_Grafo_Dirigido.java Lector.java Nodo.java Nodo_Abstracto.java Tester.java -classpath ../lib/junit__V4.4__I2007.07.19.jar
